In [1]:
import numpy as np
import cv2

In [2]:
face_cascade = cv2.CascadeClassifier('D:\\RecogX_Backup\\opencv-master\\data\\haarcascades\\haarcascade_frontalface_alt.xml')

In [3]:
image = cv2.imread('D:\\RecogX_Backup\\EL\\Image\\result\\group.jpeg')
grayImage = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
#Image is converted into Array
print(image)

[[[229 229 229]
  [229 229 229]
  [229 229 229]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]

 [[229 229 229]
  [229 229 229]
  [229 229 229]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]

 [[229 229 229]
  [229 229 229]
  [229 229 229]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]

 ...

 [[229 229 229]
  [229 229 229]
  [229 229 229]
  ...
  [231 231 231]
  [231 231 231]
  [231 231 231]]

 [[229 229 229]
  [229 229 229]
  [229 229 229]
  ...
  [231 231 231]
  [231 231 231]
  [231 231 231]]

 [[229 229 229]
  [229 229 229]
  [229 229 229]
  ...
  [231 231 231]
  [231 231 231]
  [231 231 231]]]


In [4]:
#Detects objects of different sizes in the input image. The detected objects are returned as a list of rectangles.
faces = face_cascade.detectMultiScale(grayImage)
print (faces)


[[362  28  46  46]
 [349 200  48  48]
 [432 132  46  46]
 [278 136  46  46]
 [250  43  49  49]
 [455  55  44  44]]


In [5]:
print (faces.shape)
print ("Number of faces detected: " + str(faces.shape[0]))


(6, 4)
Number of faces detected: 6


In [6]:
#No face found
if len(faces) == 0:
    print ("No faces found")
 
else:
    print (faces)
    print (faces.shape)
    print ("Number of faces detected: " + str(faces.shape[0]))
     #Draw a rectangle around the face
    for (x,y,w,h) in faces:
        cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),1)
 
    cv2.rectangle(image, ((0,image.shape[0] -25)),(270, image.shape[0]), (255,255,255), -1)
    #Add text on the image
    cv2.putText(image, "Number of faces detected: " + str(faces.shape[0]), (0,image.shape[0] -10), cv2.FONT_HERSHEY_TRIPLEX, 0.5,  (0,0,0), 1)
 
    cv2.imshow('Image with faces',image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

[[362  28  46  46]
 [349 200  48  48]
 [432 132  46  46]
 [278 136  46  46]
 [250  43  49  49]
 [455  55  44  44]]
(6, 4)
Number of faces detected: 6
